[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.gd",
    "php82Extensions.pdo_mysql",
    "php82Extensions.exif",
    "php82Extensions.zip",
    "php82Extensions.pcntl",
    "nodejs_22"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"
